// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyYpXd03J7UxaPYIyksjM3w_Wf9oQJ4cE',
    appId: '1:1008669141468:android:5d97ea92c86ff40f62c719',
    messagingSenderId: '1008669141468',
    projectId: 'commy-6c0ac',
    storageBucket: 'commy-6c0ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe-2AwMg8NwsPbkaqFJD9JNX41jIasPl4',
    appId: '1:1008669141468:ios:863686df38f58a3762c719',
    messagingSenderId: '1008669141468',
    projectId: 'commy-6c0ac',
    storageBucket: 'commy-6c0ac.appspot.com',
    iosClientId: '1008669141468-hoshda2on2urdo4t5pqbk4saknnalcue.apps.googleusercontent.com',
    iosBundleId: 'com.example.commy',
  );
}
